name: project_romance
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  # fonts & icons
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0

  #! html editor (window and mac not supported)
  html_editor_enhanced: ^2.5.1

  # Navigation 2.0
  go_router: ^13.0.1

  # State management
  flutter_bloc: ^8.1.3

  # Compare two objects
  equatable: ^2.0.5

  # Service locator
  get_it: ^7.6.4

  # Network request
  dio: ^5.3.3
  retrofit: ^4.0.3

  # json format converter
  json_annotation: ^4.8.1

  # color picker
  cyclop: ^0.7.0

  # other packages
  cached_network_image: ^3.3.0
  animated_custom_dropdown: ^2.0.0
  collection: ^1.18.0
  getwidget: ^4.0.0 # ui package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.3
  build_runner: ^2.4.6 # dart run build_runner build --delete-conflicting-outputs
flutter:
  uses-material-design: true

  fonts:
    - family: logofont
      fonts:
        - asset: assets/fonts/playball.ttf
    - family: sfpro
      fonts:
        - asset: assets/fonts/sfpro.ttf

  assets:
    - assets/
    - assets/images/
    - assets/images/support/
